// Generated by the Picture Layout Tool v4.19
//    !author: Jiang Yu-Kuan <york_jiang@mars-semi.com.tw>
//    !trail: piclay.exe lang_id -oLangID.h -xdic.xls
#ifndef _LANG_ID_H
#define _LANG_ID_H


/** Language Indexes */
typedef enum {
    L_English,
    L_End,
    L_Total = L_End
} Lang;


#endif // _LANG_ID_H
