// Generated by the Picture Layout Tool v4.19
//    !author: Jiang Yu-Kuan <york_jiang@mars-semi.com.tw>
//    !trail: piclay.exe id -oLayoutID.h layout.yaml
#ifndef _LAYOUT_ID_H
#define _LAYOUT_ID_H


/** IDs of Layout */
typedef enum {
    LAY_LiveView_Bg,
    LAY_LiveViewSingle_Background,
    LAY_LiveViewSingle_Button,
    LAY_LiveViewSingle_ButtonTouch,
    LAY_LiveViewPIP_Bg,
    LAY_LiveViewPIP_Background,
    LAY_LiveViewPIP_Button,
    LAY_End,
    LAY_Total = LAY_End
} LayoutID;


#endif // _LAYOUT_ID_H
