// Generated by the Picture Layout Tool v4.19
//    !author: Jiang Yu-Kuan <york_jiang@mars-semi.com.tw>
//    !trail: piclay.exe msg_id -oMsgID.h -xdic.xls layout.yaml
#ifndef _MSG_ID_H
#define _MSG_ID_H


/** IDs of Messages */
typedef enum {
    MSG_SdOn,
    MSG_SdOff,
    MSG_HddOn,
    MSG_HddOff,
    MSG_LightOn,
    MSG_End,
    MSG_Total = MSG_End
} MsgID;


#endif // _MSG_ID_H
